const std = @import("std");
const types = @import("types.zig");
const LogEntry = types.LogEntry;

pub const FlameGraphGenerator = struct {
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) FlameGraphGenerator {
        return .{ .allocator = allocator };
    }

    pub fn generate(self: *FlameGraphGenerator, entries: []const LogEntry, trace_id: []const u8, output_path: []const u8) !void {
        const filtered = try self.filterByTraceId(entries, trace_id);
        defer self.allocator.free(filtered);

        if (filtered.len == 0) {
            return error.NoEntriesForTraceId;
        }

        var sorted = try self.allocator.dupe(LogEntry, filtered);
        defer {
            for (sorted) |*e| {
                e.deinit(self.allocator);
            }
            self.allocator.free(sorted);
        }

        std.mem.sort(LogEntry, sorted, {}, compareByTimestampMs);

        const file = try std.fs.cwd().createFile(output_path, .{});
        defer file.close();

        const writer = file.writer();

        try self.writeHeader(writer, trace_id, sorted);

        try self.writeServiceCallStacks(writer, sorted);

        try self.writeSummary(writer, sorted);
    }

    fn compareByTimestampMs(_: void, a: LogEntry, b: LogEntry) bool {
        return a.timestamp_ms < b.timestamp_ms;
    }

    fn filterByTraceId(self: *FlameGraphGenerator, entries: []const LogEntry, trace_id: []const u8) ![]const LogEntry {
        var list = std.ArrayList(LogEntry).init(self.allocator);
        defer list.deinit();

        for (entries) |entry| {
            if (std.mem.eql(u8, entry.trace_id, trace_id)) {
                const dup = try self.dupeEntry(entry);
                try list.append(dup);
            }
        }

        return list.toOwnedSlice();
    }

    fn dupeEntry(self: *FlameGraphGenerator, entry: LogEntry) !LogEntry {
        return LogEntry{
            .timestamp_ms = entry.timestamp_ms,
            .timestamp = entry.timestamp,
            .service = try self.allocator.dupe(u8, entry.service),
            .trace_id = try self.allocator.dupe(u8, entry.trace_id),
            .level = try self.allocator.dupe(u8, entry.level),
            .message = try self.allocator.dupe(u8, entry.message),
            .raw = try self.allocator.dupe(u8, entry.raw),
            .color = try self.allocator.dupe(u8, entry.color),
            .duration_ms = entry.duration_ms,
        };
    }

    fn writeHeader(self: *FlameGraphGenerator, writer: anytype, trace_id: []const u8, entries: []const LogEntry) !void {
        _ = self;
        try writer.print("# Flame Graph Data for Trace-ID: {s}\n", .{trace_id});
        try writer.print("# Generated by trace-cli\n", .{});
        try writer.print("# Total entries: {}\n", .{entries.len});
        if (entries.len > 0) {
            const total_duration = entries[entries.len - 1].timestamp_ms - entries[0].timestamp_ms;
            try writer.print("# Total duration: {} ms\n", .{total_duration});
        }
        try writer.print("# Format: stack;frames duration_ms\n", .{});
        try writer.print("\n", .{});
    }

    fn writeServiceCallStacks(self: *FlameGraphGenerator, writer: anytype, entries: []const LogEntry) !void {
        if (entries.len < 2) return;

        var stack = std.ArrayList([]const u8).init(self.allocator);
        defer stack.deinit();

        var service_set = std.StringHashMap(void).init(self.allocator);
        defer service_set.deinit();

        for (entries) |entry| {
            if (!service_set.contains(entry.service)) {
                try service_set.put(try self.allocator.dupe(u8, entry.service), {});
            }
        }

        for (entries, 0..) |entry, i| {
            if (i == 0) {
                try stack.append(entry.service);
                continue;
            }

            const prev_entry = entries[i - 1];
            const duration = entry.timestamp_ms - prev_entry.timestamp_ms;

            var current_stack = std.ArrayList([]const u8).init(self.allocator);
            defer current_stack.deinit();

            try current_stack.append("trace");
            try current_stack.append(entry.service);

            const stack_str = try joinStrings(self.allocator, current_stack.items, ";");
            defer self.allocator.free(stack_str);

            const actual_duration = if (prev_entry.duration_ms) |d| d else duration;
            const display_duration = @max(actual_duration, 1);

            try writer.print("{s} {}\n", .{ stack_str, display_duration });

            if (i < entries.len - 1) {
                const next_entry = entries[i + 1];
                const next_duration = next_entry.timestamp_ms - entry.timestamp_ms;
                const service_stack = try std.fmt.allocPrint(self.allocator, "trace;{s};{s}", .{ entry.service, next_entry.service });
                defer self.allocator.free(service_stack);
                try writer.print("{s} {}\n", .{ service_stack, @max(next_duration, 1) });
            }
        }

        if (entries.len >= 2) {
            const total_duration = entries[entries.len - 1].timestamp_ms - entries[0].timestamp_ms;
            try writer.print("trace {}\n", .{@max(total_duration, 1)});
        }
    }

    fn writeSummary(self: *FlameGraphGenerator, writer: anytype, entries: []const LogEntry) !void {
        if (entries.len < 2) return;

        try writer.print("\n", .{});
        try writer.print("# Detailed timing breakdown:\n", .{});

        for (entries, 0..) |entry, i| {
            if (i == 0) continue;

            const prev = entries[i - 1];
            const duration = entry.timestamp_ms - prev.timestamp_ms;
            const actual_duration = if (prev.duration_ms) |d| d else duration;

            try writer.print("# [{s}] {s} -> {s}: {} ms\n", .{
                prev.level,
                prev.service,
                entry.service,
                actual_duration,
            });
        }

        const total_duration = entries[entries.len - 1].timestamp_ms - entries[0].timestamp_ms;
        try writer.print("# Total request duration: {} ms\n", .{total_duration});
    }

    pub fn generatePerServiceStats(self: *FlameGraphGenerator, entries: []const LogEntry, trace_id: []const u8) !void {
        const filtered = try self.filterByTraceId(entries, trace_id);
        defer self.allocator.free(filtered);

        if (filtered.len < 2) return;

        var sorted = try self.allocator.dupe(LogEntry, filtered);
        defer {
            for (sorted) |*e| {
                e.deinit(self.allocator);
            }
            self.allocator.free(sorted);
        }

        std.mem.sort(LogEntry, sorted, {}, compareByTimestampMs);

        var service_times = std.StringHashMap(i64).init(self.allocator);
        defer {
            var it = service_times.keyIterator();
            while (it.next()) |key| {
                self.allocator.free(key.*);
            }
            service_times.deinit();
        }

        for (sorted, 0..) |entry, i| {
            if (i == 0) continue;
            const prev = sorted[i - 1];
            const duration = entry.timestamp_ms - prev.timestamp_ms;

            const gop = try service_times.getOrPut(prev.service);
            if (!gop.found_existing) {
                gop.key_ptr.* = try self.allocator.dupe(u8, prev.service);
                gop.value_ptr.* = 0;
            }
            gop.value_ptr.* += duration;
        }

        const stdout = std.io.getStdOut().writer();
        try stdout.print("\nPer-Service Time Breakdown for Trace-ID: {s}\n", .{trace_id});
        try stdout.print("========================================\n", .{});

        const total_duration = sorted[sorted.len - 1].timestamp_ms - sorted[0].timestamp_ms;

        var it = service_times.iterator();
        while (it.next()) |kv| {
            const percentage = @as(f64, @floatFromInt(kv.value_ptr.*)) / @as(f64, @floatFromInt(total_duration)) * 100;
            const bar_len: usize = @intFromFloat(percentage / 2);
            const bar = try self.allocator.alloc(u8, bar_len);
            defer self.allocator.free(bar);
            @memset(bar, '=');

            try stdout.print("{s:<10} {:>6} ms ({:>5.1}%) |{s}\n", .{
                kv.key_ptr.*,
                kv.value_ptr.*,
                percentage,
                bar,
            });
        }

        try stdout.print("\nTotal: {} ms\n", .{total_duration});
    }
};

fn joinStrings(allocator: std.mem.Allocator, strings: []const []const u8, separator: []const u8) ![]u8 {
    if (strings.len == 0) return allocator.alloc(u8, 0);

    var total_len: usize = 0;
    for (strings) |s| {
        total_len += s.len;
    }
    total_len += separator.len * (strings.len - 1);

    const result = try allocator.alloc(u8, total_len);
    var current: usize = 0;

    for (strings, 0..) |s, i| {
        if (i > 0) {
            @memcpy(result[current .. current + separator.len], separator);
            current += separator.len;
        }
        @memcpy(result[current .. current + s.len], s);
        current += s.len;
    }

    return result;
}
